#ifndef _CONSTANT_H_
#define _CONSTANT_H_

#define LIDAR_NUM 1
#define LIDAR_MEA_MAX_ANG 90
#define LIDAR_MEA_MIN_ANG 30
#define LIDAR_MEA_TIME 3

#define VL53_HEIGHT 11.3
#define VL53_SHUTDOWN_PIN_START 5
#define VL53_MEASUREMENT_MAX 1000

#define CAR_WIDTH 30.0
#define TRACK_WIDTH 100.0

#endif